platform :ios, '8.0'
target "UIProject" do
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.8.1’
pod ‘Masonry’, '~> 1.0.1’
pod 'BaiduMapKit' #百度地图SDK
pod 'AFNetworking', '~> 3.1.0'
pod 'AVOSCloud'             
pod 'AVOSCloudIM'      
pod 'AVOSCloudCrashReporting'
end
